### ISSUE TITLE
data table bug after compiler speed improvements

### ISSUE THREAD

**Issue by tdhock** [tdhock/animint2#74]
#63 started using data.table for improving the speed of the compiler, but that seems to cause an error when compiling some animints. I'm surprised we did not catch this in our test suite, why not?
```r
year.int <- as.integer(floor(time(co2)))
month.int <- as.integer(time(co2) %% 1 * 12 + 1)
year.month.chr <- sprintf("%d-%02d-15", year.int, month.int)
year.month.POSIXct <- as.POSIXct(strptime(year.month.chr, "%Y-%m-%d"))
month.str <- strftime(year.month.POSIXct, "%B")
month <- factor(month.str, month.str[1:12])
library(data.table)
co2.details <- data.table(
  year.int,
  month.int,
  month,
  year.month.POSIXct,
  ppm=as.numeric(co2))
library(animint2)
TimeSeries <- ggplot()+
  geom_line(aes(year.month.POSIXct, ppm),
            size=1,
            data=co2.details)+
  geom_point(aes(year.month.POSIXct, ppm, color=month),
             data=co2.details)+
  xlab("Time of measurement")+
  ylab("Atmospheric carbon dioxide (parts per million)")
animint(
  TimeSeries,
  first=list(month=c("May", "October")))
```
I get:
```r
> animint(
+ TimeSeries,
+ first=list(month=c("May", "October")))
Saving animint in temporary directory; specify output directory using animint(out.dir="path/to/directory")
Error in `[.data.table`(L$data, , s.name) : 
  j (the 2nd argument inside [...]) is a single symbol but column name 's.name' is not found. Perhaps you intended DT[, ..s.name]. This difference to data.frame is deliberate and explained in FAQ 1.1.
```
@Faye-yufan can you please investigate and fix?

**Comment by Faye-yufan** [comment]
Will do!

**Comment by Faye-yufan** [comment]
Hi @tdhock , this bug may be caused by passing `data.table` into the data param instead of `data.frame`. 
```R
geom_line(aes(year.month.POSIXct, ppm),
            size=1,
            data=co2.details) # here we normally pass data.frame
```
The error is from [`addShowSelectedForLegend`](https://github.com/tdhock/animint2/blob/3ce09f1e524a0f6c5e351dcf90988ece5f91c01a/R/z_animintHelpers.R#L18) function, which is not a part of the code we use data.table to improve speed. In this function, `L$data` is passed in from the original `plot$data`, that is the data.table, but it is treated as df in this func.

The reason why our test suite didn't catch this error is that they all use `data.frame` as the source data(correct me if I'm wrong, as I just took a quick look at our tests). 

A temporary solution to this would be convert the dt to df:
```R
co2.details <- as.data.frame(co2.details)
```
Or change the function into `data.table` syntax to make it work.

**Comment by tdhock** [comment]
thanks for the very clear explanation, that makes sense and is very helpful.
we should add this as a test case.
another solution to fix this issue is to just convert the input data to a frame.

**Comment by tdhock** [comment]
hi @Faye-yufan any updates on this issue? I would suggest fixing this before moving on to other things.

**Comment by Faye-yufan** [comment]
hi @tdhock  I'm on it now! By converting the input to a df.
